language: python
sudo: false
env:
  matrix:
  - TEST_DOCTESTS="true" FASTCACHE="false" TEST_SETUP="true"
  - SPLIT="1/4" TEST_SYMPY="true"
  - SPLIT="2/4" TEST_SYMPY="true"
  - SPLIT="3/4" TEST_SYMPY="true"
  - SPLIT="4/4" TEST_SYMPY="true"
  global:
    - secure: "YIEZal9EBTL+fg2YmoZoS8Bvt3eAVUOZjb38CtqpzR2CCSXWoUk35KG23m2NknlY1iKfYJyt7XWBszT/VKOQEbWQq7PIakV4vIByrWacgBxy1x3WC+rZoW7TX+JJiL+y942qIYbMoNMMB8xFpE5RDLSjSecMpFhJJXoafVTvju8="
dist: trusty

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - TEST_ASCII="true"
        # space separated list of optional dependencies(conda packages) to install and test
        - TEST_OPT_DEPENDENCY="numpy scipy gmpy2 matplotlib>=2.2 theano llvmlite autowrap cython wurlitzer python-symengine=0.3.* tensorflow numexpr ipython antlr-python-runtime>=4.7,<4.8 antlr>=4.7,<4.8 cloudpickle"
      addons:
        apt:
          packages:
            # for theano
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
    - python: 3.6
      env:
        - TEST_ASCII="true"
        - TEST_OPT_DEPENDENCY="numpy scipy gmpy2 matplotlib theano llvmlite autowrap cython wurlitzer python-symengine=0.3.* tensorflow numexpr ipython antlr-python-runtime>=4.7,<4.8 antlr>=4.7,<4.8 cloudpickle"
        - TEST_SAGE="true"
      addons:
        apt:
          packages:
            # for theano
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - python-scipy

    - python: 3.6
      env:
        - TEST_SPHINX="true"
        - FASTCACHE="false"
      addons:
        apt:
          packages:
            - graphviz
            - inkscape
            - texlive
            - texlive-xetex
            - texlive-fonts-recommended
            - texlive-latex-extra
            - latexmk
            - lmodern
            - librsvg2-bin
            - imagemagick
            - docbook2x

    - python: 2.7
      env:
        - TEST_SLOW="true"
        - SPLIT="1/3"
    - python: 2.7
      env:
        - TEST_SLOW="true"
        - SPLIT="2/3"
    - python: 2.7
      env:
        - TEST_SLOW="true"
        - SPLIT="3/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="1/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="2/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="3/3"

    # Everything here and below is in the allow_failures. The need to be
    # duplicated here and in that section below.
    - python: "pypy"
      env:
        - TEST_DOCTESTS="true"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="1/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="2/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="3/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="4/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy

  allow_failures:
    # PyPy randomly fails because of some PyPy bugs (Fatal RPython error: AssertionError)
    - python: "pypy"
      env:
        - TEST_DOCTESTS="true"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="1/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="2/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="3/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="4/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy

before_install:
  - set -e
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - |
    if [[ -n "${TEST_OPT_DEPENDENCY}" ]]; then
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
        deactivate; # Deactivate the Travis virtualenv
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -q -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -q -O miniconda.sh;
        fi
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
        hash -r;
        conda config --set always_yes yes --set changeps1 no;
        conda update -q conda;
        conda config --prepend channels conda-forge --prepend channels symengine/label/dev;

        conda info -a;
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION ${TEST_OPT_DEPENDENCY};
        source activate test-environment;
        export CPATH=$CONDA_PREFIX/include;
        export LIBRARY_PATH=$CONDA_PREFIX/lib;
        export LD_LIBRARY_PATH=$CONDA_PREFIX/lib;
        export SYMPY_STRICT_COMPILER_CHECKS=1;
        conda clean --all;
        if [[ "$TEST_SAGE" == "true" ]]; then
            # Use a separate environment because sage downgrades matplotlib
            conda create -c conda-forge/label/cf201901 -n sage sagelib mpmath "ipython>=5.5.0,<6";
            conda clean --all;
        fi
        if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
            conda install matchpy;
        fi
    elif [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then
        pip list | grep "numpy" && pip uninstall -y numpy;
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      pip install "sphinx" "docutils" doctr matplotlib;
    fi

install:
  # If a command fails, fail the build.
  - set -e
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ];
      then virtualenv -p /usr/bin/pypy ~/.venv;
           . ~/.venv/bin/activate;
    fi
  # Once https://github.com/fredrik-johansson/mpmath/pull/403 is in a released
  # version of mpmath remove this line.
  - pip install mpmath
  # -We:invalid makes invalid escape sequences error in Python 3.6. See
  # -#12028.
  - |
    if [[ "${TEST_SETUP}" == "true" ]]; then
      # The install cycle below is to test installation on systems without
      # setuptools.
      virtualenv ~/.venv-no-setuptools;
      ~/.venv-no-setuptools/bin/pip install mpmath;
      ~/.venv-no-setuptools/bin/pip uninstall -y setuptools;
      ~/.venv-no-setuptools/bin/python -We:invalid setup.py -q install;
    fi
    python -We:invalid -m compileall -f sympy/;
    python -We:invalid setup.py -q install;
    pip list --format=columns;

script:
  # Don't run doctr if the build fails
  - set -e
  - bin/test_travis.sh
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
        doctr deploy dev --deploy-repo sympy/sympy_doc --command './generate_indexes.py';
    fi
notifications:
  email: false
